language: python

python:
  - "3.6.8"

env:
  global
    - PYTHONPATH="/home/travis/build/joacorapela/gaussianProcesses/src/gaussianProcesses"

install:
  - pip install -r requirements.txt

script:
  - pytest
